- project:
    name: madhuripatil2/zuul-test
    check:
      jobs:
        - testjob
        - noop

- job:
    name: testjob
    parent: base
    run: testjob.yaml
    nodeset:
      nodes:
        - name: builder
          label: ubuntu-xenial
    secrets:
      - secret1

